apiVersion: v2
name: rest-trans
description: A Helm chart for rest-trans API
type: application
version: 0.8.0
appVersion: "0.8.0"
icon: https://raw.githubusercontent.com/laurentpoirierfr/rest-trans/main/assets/icon.png
maintainers:
  - name: laurentpoirierfr
