apiVersion: v2
name: rest-trans
description: A Helm chart for rest-trans API
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/laurentpoirierfr/rest-trans/main/assets/icon.png
maintainers:
  - name: laurentpoirierfr
