apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rest-trans.fullname" . }}
  labels:
    {{- include "rest-trans.labels" . | nindent 4 }}
type: Opaque
data:
  REST_DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
